### ISSUE TITLE
「ふ」が「fu」になっているものがある

### ISSUE THREAD

**Issue by myakura** [decomoji/slack-reaction-decomoji#108]
目当てのデコモジがあるか探しているなか見つけたのですが、

![台風接近](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/taifuusekkinn.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/taifuusekkinn.png)

このファイル名が "taifuusekkinn" となっておりました。命名規則を見るに、"taihuusekkinn" となるかと思いますがいかがでしょうか。

また、

![フィフー](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/fifu-.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/fifu-.png)

も "fifu-" となっていました。

どちらも固有名詞でしたらすみません。

**Comment by oti** [comment]
ありがとうございます。それらはこちらのミスなので、次で直します。

**Comment by myakura** [comment]
ありがとうございます。気になったのでおせっかいながら他にもないか探してみました。

「じょ」で「jo」になっている。

![入場禁止](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/nyuujoukinnsi.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/nyuujoukinnsi.png)

![バージョン上げて](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/ba-jonnagete.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/ba-jonnagete.png)

![バージョン下げて](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/ba-jonnsagete.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/ba-jonnsagete.png)

「し」で「shi」になっている。

![せやしな](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/seyashina.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/seyashina.png)

![よしな力](https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/yoshinaryoku.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.19.1/decomoji/extra/yoshinaryoku.png)

**Comment by oti** [comment]
@myakura v5.20.0 でタイポを修正しました。

![台風接近](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/taihuusekkinn.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/taihuusekkinn.png)

![フィフー](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/fihu-.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/fihu-.png)

![入場禁止](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/nyuuzyoukinnsi.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/nyuuzyoukinnsi.png)

![バージョン上げて](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/ba-zyonnagete.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/ba-zyonnagete.png)

![バージョン下げて](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/ba-zyonnsagete.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/ba-zyonnsagete.png)

![せやしな](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/seyasina.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/seyasina.png)

![よしな力](https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/yosinaryoku.png?raw=true)
(https://github.com/decomoji/decomoji/blob/v5.20.0/decomoji/extra/yosinaryoku.png)

報告ありがとうございました！
