### ISSUE TITLE
Node 16番台で動かない

### ISSUE THREAD

**Issue by Tsuion** [decomoji/slack-reaction-decomoji#112]
指定されているNodeV14～ではnpmが同梱されていないため、NodeV16.16.0(最新LTS)で実行したところ、
`npm ci`までは動作するが、nodeが実行できないという問題が発生しました。NodeV16～への対応を要望します。
よろしくお願いします
吐き出されたエラー(理解できませんでした)
```shell
'grep' �́A�Ք�R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
node:child_process:902
    throw err;
    ^

Error: Command failed: git tag --list | sort -V | grep -E ^v5
'grep' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at getGitTagArray (C:\Users\2021007292\OneDrive - tokyoeducation\デスクトップ\decomoji\decomoji\scripts\utilities\getGitTagArray.js:9:24)
    at Object.<anonymous> (C:\Users\2021007292\OneDrive - tokyoeducation\デスクトップ\decomoji\decomoji\scripts\manager\modules\askInputs.js:79:29)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  status: 255,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(114) [Uint8Array] [
       39, 103, 114, 101, 112,  39,  32, 130, 205, 129,  65, 147,
      224, 149, 148, 131,  82, 131, 125, 131, 147, 131, 104, 130,
      220, 130, 189, 130, 205, 138,  79, 149, 148, 131,  82, 131,
      125, 131, 147, 131, 104, 129,  65,  13,  10, 145, 128, 141,
      236, 137, 194, 148,  92, 130, 200, 131, 118, 131, 141, 131,
       79, 131, 137, 131, 128, 130, 220, 130, 189, 130, 205, 131,
      111, 131,  98, 131,  96,  32, 131, 116, 131,  64, 131,  67,
      131, 139, 130, 198, 130, 181, 130, 196, 148,  70, 142, 175,
      130, 179, 130, 234,
      ... 14 more items
    ]
  ],
  pid: 9220,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(114) [Uint8Array] [
     39, 103, 114, 101, 112,  39,  32, 130, 205, 129,  65, 147,
    224, 149, 148, 131,  82, 131, 125, 131, 147, 131, 104, 130,
    220, 130, 189, 130, 205, 138,  79, 149, 148, 131,  82, 131,
    125, 131, 147, 131, 104, 129,  65,  13,  10, 145, 128, 141,
    236, 137, 194, 148,  92, 130, 200, 131, 118, 131, 141, 131,
     79, 131, 137, 131, 128, 130, 220, 130, 189, 130, 205, 131,
    111, 131,  98, 131,  96,  32, 131, 116, 131,  64, 131,  67,
    131, 139, 130, 198, 130, 181, 130, 196, 148,  70, 142, 175,
    130, 179, 130, 234,
    ... 14 more items
  ]
}
```

**Comment by Tsuion** [comment]
追記　
カスタム絵文字マネージャーや手動で登録しても、"これは画像ファイルですか？"的なエラーが出てしまい、非常に手間取る事態です。Slack本体のバグである可能性もあります。

**Comment by oti** [comment]
報告ありがとうございます。

他の多くのOSSと同様に、自リポジトリが指定するバージョン以外の Node.js での動作は保証外というのが基本方針となります。なお、Node.js 14.15.4 には npm 6.14.10 が同梱されているはずなので併せてご確認ください。

https://nodejs.org/ja/download/releases/

追加コメントの内容から察するにバイナリファイルが壊れているように思います。下記を試すと解決するかもしれません。

- Node.js v14.15.4 を使う
- git clone し直す
- git clone でダメなら Download ZIP して試す
- OneDrive ではないディレクトリで試す

---

一旦 [wontfix] タグをつけますが、しばらくは open のままにしておくので、正常に動作するようになったなどの追加報告があればコメントいただければと思います。

**Comment by Tsuion** [comment]
おはようございます。
Node.jsV14.15.4で再試行してみましたが、同じエラーが出ました。またディレクトリも変更しましたが、上手くいきませんでした。😢
git cloneで失敗している感じはしないのですが、もう一度zipでダウンロードして試してみます。
もしかしたらこちらの端末がよろしくないのかもしれません…

**Comment by ginpei** [comment]
@Tsuion こんにちは！

エラーメッセージ中のファイルパスから Windows 環境かなと考えています。

> 'grep' �́A�Ք�R�}���h�܂��͊O���R�}���h�A

文字化けしていて読めませんが、もしかして「grep がない」エラーかもしれません。以下の `where grep` というコマンドでインストール済みか確認してみてもらえませんか。インストールされているパスが表示されればインストール済み、見つからない系のメッセージ（また文字化けしてるかも）が出ればインストールされていません。

```
>where grep
C:\Program Files (x86)\Gow\bin\grep.exe
```

`grep` は Windows には標準搭載されていないもののはずなので、別途インストールが必要です。

[Gow](https://github.com/bmatzelle/gow/wiki) というツールで `grep` 等 Linux 系コマンドをインストールすることができます。Gow のインストールには [Windows 標準の `winget` コマンド](https://docs.microsoft.com/en-us/windows/package-manager/winget/)が便利です。（管理者権限が必要なので学校会社等の所属団体のポリシーもご確認ください。）

```
>winget install gow
```

（不要になったら `winget uninstall gow` でアンインストールできます。）

それはそれとして、これが気になりますね。

>  カスタム絵文字マネージャーや手動で登録しても、"これは画像ファイルですか？"的なエラーが出て

よければこれらも試してもらえますか。

- decomoji でない何か他の画像は手動で登録できるか（Slack が正常に動作していることの確認）
- エラーになる decomoji の画像ファイルを画像編集ソフトで開けるか（壊れていないことの確認）
- 該当エラーメッセージ全文を共有（エラー詳細を把握）
  - コピペでもスクショでも構いません
- エラーになる decomoji の画像ファイルをここで共有（別環境で試したい）
  - このコメント入力欄にドラッグ＆ドロップでできるはず
  - または、OneDrive のファイルを右クリックから共有して URL をここへ貼り付け

お手すきの際によろしくお願いします。

**Comment by Tsuion** [comment]
こんにちは😃
手元に端末がなかったため、issueおくれました。申し訳ないです😔
今日の午後中に再試行&スクショをしておきます。
GREPはインストールした記憶がないので、恐らく原因はそれですね…

**Comment by oti** [comment]
#122 Node.js v18 にアップデートしたので close します。
