### ISSUE TITLE
今日はガチが :kyouhabati:

### ISSUE THREAD

**Issue by Ikazuchisdiary** [decomoji/slack-reaction-decomoji#115]
bとgをtypoしてるっぽいです

https://finder.decomoji.dev/?size=ll&category=basic,extra&search=kyouhabati&extra=kyouhabati

**Comment by oti** [comment]
報告ありがとうございます。デコモジの typo 修正は[マイナーアップデートの対象](https://github.com/decomoji/decomoji/blob/main/docs/UPDATING_POLICY.md#%E3%83%9E%E3%82%A4%E3%83%8A%E3%83%BC%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88)となっており、慣例では新規デコモジ追加と同じタイミングで対応しています。

こちらの fix は少し先になってしまいますが、必ず対応しますので気長にお待ちいただけると幸いです:bow:

**Comment by oti** [comment]
@Ikazuchisdiary お待たせしました。v5.22 にて修正しました。報告ありがとうございました。
https://finder.decomoji.dev/?search=kyouhagati
