### ISSUE TITLE
ナウでヤング のファイル名typo

### ISSUE THREAD

**Issue by torut** [decomoji/slack-reaction-decomoji#116]
https://finder.decomoji.dev/?size=ll&category=basic,extra&search=yaudeyanngu

`yaudeyanngu` → `naudeyanngu` のtypoでしょうか？

**Comment by oti** [comment]
報告ありがとうございます。デコモジの typo 修正は[マイナーアップデートの対象](https://github.com/decomoji/decomoji/blob/main/docs/UPDATING_POLICY.md#%E3%83%9E%E3%82%A4%E3%83%8A%E3%83%BC%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88)となっており、慣例では新規デコモジ追加と同じタイミングで対応しています。

こちらの fix は少し先になってしまいますが、必ず対応しますので気長にお待ちいただけると幸いです:bow:

**Comment by oti** [comment]
@torut お待たせしました。v5.22 で修正いたしました。報告ありがとうございました。
https://finder.decomoji.dev/?search=naudeyanngu
