### ISSUE TITLE
でかした :dekasita: が欲しい

### ISSUE THREAD

**Issue by ginpei** [decomoji/slack-reaction-decomoji#3]
褒めてあげたい

![211](https://cloud.githubusercontent.com/assets/355808/10582222/a8596244-763b-11e5-8ad6-40da4da8482f.gif)

`:erai:` と重複？

**Comment by oti** [comment]
英訳しだいですかね。

`:erai:` を「立場がえらい」というニュアンスに変えて、"You're great!" を `:dekasita:` を充てればいいかなーと思います。

ということで代替の英訳プリーズ！

**Comment by oti** [comment]
`:erai:` は "You're great!" のままで、 `:dekasita:` は "Well done!" とかでいい気がしてきた。

**Comment by oti** [comment]
@ginpei done!

**Comment by ginpei** [comment]
![:dekasita:](https://raw.githubusercontent.com/oti/slack-reaction-decomoji/master/dist/dekasita.png)
