### ISSUE TITLE
:hai: が利用できない

### ISSUE THREAD

**Issue by azusa-tomita** [decomoji/slack-reaction-decomoji#33]
:hai: のみ、登録しようとすると「残念ながら、国際標準絵文字セットにはすでに hai という名前のものが含まれています。別の名前を試してみますか？」と返されて登録できない
<img width="1034" alt="b0d29eac6e4bdbdf9c023701222ff347" src="https://user-images.githubusercontent.com/869036/33412726-af2a5a00-d5d0-11e7-9d16-2c9942e9618a.png">
<img width="1124" alt="7ebd8a33962e3179ebab7ae360db984c" src="https://user-images.githubusercontent.com/869036/33412734-b704db2e-d5d0-11e7-8019-e1280e4c9045.png">

**Comment by oti** [comment]
:hai: が登録できないのに、そのチームで :hai: を出そうとしても出てこないんですなぁ……。

ちょっと調査に時間がかかりそうですが、

- [x] 1. 新規にSlackチームを作り、 :hai: が登録できるか
- [ ] 2. 既存のSlackチームで :hai: がないチームを探し、登録できるか
- [ ] 3. 既存のSlackチームで :hai: があるチームを探し、:hai: を一旦削除して、再登録できるか

考えられる結果は、

- [x] 新規チームは :hai: が登録できない
- [ ] 既存チームでも :hai: が登録できない
- [ ] 既存チームで :hai: がすでにある場合に一度消すと登録できないくなる
- [ ] 既存チームで :hai: がすでにある場合に一度消しても再登録できる
- [ ] 既存チームでも登録できるのとできないのがある（どこかの時期で変わった）

あたりでしょうか。

先にSlack公式で、国際標準絵文字セットについての何かを探してみようと思います。

**Comment by oti** [comment]
よくわからなかった。

`:hai:` を `:hai_:` に変えることでこの問題を回避することにします。

**Comment by oti** [comment]
fix 6d6be3
