### ISSUE TITLE
すぐタイポがすぐ卑猥

### ISSUE THREAD

**Issue by masuP9** [decomoji/slack-reaction-decomoji#35]
`sugutaipo` が ![すぐ卑猥](https://raw.githubusercontent.com/decomoji/slack-reaction-decomoji/master/decomoji/sugutaipo.png) の画像ファイルになってしまってる。

https://github.com/decomoji/slack-reaction-decomoji/blob/master/decomoji/sugutaipo.png

**Comment by oti** [comment]
まじかよ直します

**Comment by oti** [comment]
Fix.
https://github.com/decomoji/slack-reaction-decomoji/commit/0d6022ae334902b9639e96cb8edc530a72644084

**Comment by masuP9** [comment]
![さすがだ](https://raw.githubusercontent.com/decomoji/slack-reaction-decomoji/master/decomoji/sasugada.png)
