### ISSUE TITLE
スクリプトを使って登録するときに、登録するデコモジを絞り込めるようにしたい

### ISSUE THREAD

**Issue by kubosho** [decomoji/slack-reaction-decomoji#37]
たとえば悪口系（ [butayarou.png](https://github.com/decomoji/slack-reaction-decomoji/blob/master/decomoji/butayarou.png) や [kuso.png](https://github.com/decomoji/slack-reaction-decomoji/blob/master/decomoji/kuso.png)）や、エロ系（[gazoutikanu.png](https://github.com/decomoji/slack-reaction-decomoji/blob/master/decomoji/gazoutikanu.png) や [oppai.png](https://github.com/decomoji/slack-reaction-decomoji/blob/master/decomoji/oppai.png)）など、Slackのグループによっては登録するのに躊躇してしまうデコモジがあるため、何らかの手段でインポートするデコモジを絞り込めると良さそうと思いました。

## 発生しそうな作業の一覧

- `decomoji/` ディレクトリ内で階層分け
- https://github.com/decomoji/slack-reaction-decomoji/blob/master/scripts/import.rb の変更

**Comment by oti** [comment]
現状、ハイコンテキストすぎるデコモジたちがフラットに置かれているので、これはあまりよくないなとは思っていました。

- 基本セットと拡張パックのような形でディレクトリを分ける
- 拡張パックのインストールはimport.rbにオプションを渡して実行する形に変える

概ねこの対応で進めたいと考えています。

**Comment by oti** [comment]
v4で対応予定です

**Comment by oti** [comment]
#38 で対応しました！
