### ISSUE TITLE
Need uninstaller or migration tool

### ISSUE THREAD

**Issue by PicoSushi** [decomoji/slack-reaction-decomoji#40]
v4リリースおめでとうございます 🎉 

現在、v3導入済み環境からv4へのアップデートを計画しているのですが、既存デコモジの色・フォント変更が含まれてるとのことで、一旦既存のデコモジを削除しようとしています。

そこで、アンインストーラー、または移行用のツールがあると便利かと考え、Issueを立てさせて頂きました。

また、アンインストーラーの実装方法としては以下が考えられます。
- 指定したバージョンで登録されるemojiを全部削除
  - decomoji以外で登録したemojiが削除される可能性がある？
- 指定したバージョンで登録されるemojiを一旦取得し、ファイルが同一か判断して削除
  - 該当するバージョンのファイルか、ハッシュ値を持っておく必要がある
  - 時間が掛かる

以上、ご検討頂ければ幸いです。

**Comment by geckotang** [comment]
アンインストーラに関しての懸念点は次のとおりです

- Slackのアカウントの権限にもよるのですが、自身が追加したアイコンのみ削除できるため、他人が追加したデコモジは削除することができません。
- 登録に使用したファイル名と、実際に登録されたファイル名は異なる
- 登録されているCustom EmojiのNameとデコモジの名前が一致するとは限らない
    - 手動で登録する場合にNameが変更が可能である
    - エイリアスが貼られている場合があるため

別案としては、絵文字の登録をサポートするChrome拡張 [Neutral Face Emoji Tools](https://chrome.google.com/webstore/detail/neutral-face-emoji-tools/anchoacphlfbdomdlomnbbfhcmcdmjej) のように、Chrome拡張などで削除しやすい仕組みを作ってみる。という手もあるかなと思います（デコモジはあまり関係なくなりそうですが）。

**Comment by oti** [comment]
アンインストーラーについてはわたし個人も欲しいと思っています。
しかし @geckotang の言う通り、権限的な問題、登録ファイル名の保証ができない問題があり、仮に実行するとそのチームの環境を壊してしまうことが大きな懸念となっています。
同じ理由でアファベットをヘボン式にしたエイリアスを登録するツールも作らないでいます。

decomojiが800個を超え、一旦登録すると管理できない規模になっていることは認識していますが、これをどう対応したらよいものかベターな方法を見出せないでいるのが現状です。

今となっては遅いのですが、ファイル名にサフィックスがあったなら入力にも判定にも困らなかったかもしれないと後悔しています。

**Comment by PicoSushi** [comment]
ご検討ありがとうございました！

さしあたり、手動での削除で対応しようかと思います。

**Comment by oti** [comment]
🙇
