### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by PicoSushi** [decomoji/slack-reaction-decomoji#43]
On import, I got error as below:
```
importing kannzenndoui...
Traceback (most recent call last):
        4: from import.rb:69:in `<main>'
        3: from import.rb:14:in `import_decomojis'
        2: from import.rb:52:in `upload_decomojis'
        1: from import.rb:52:in `each'
import.rb:61:in `block in upload_decomojis': undefined method `[]=' for nil:NilClass (NoMethodError)
```

note: I've already imported with older version (v4.x?) of decomoji on that Slack team which error occurred.

**Comment by PicoSushi** [comment]
#42 を手元でマージしたところ正常に動きましたので、どうやら言及されているようにSlack側での変更が原因のようでした。

**Comment by oti** [comment]
@PicoSushi レスできずすみませんー！　#42 をマージしてうまくいったとのことでよかったです。早いうちにあちらをマージしますので、そしたらまたメンションしますね。

それまでこのissueはopenのままでさせてください。

**Comment by oti** [comment]
@PicoSushi @wktk #42 マージしましたのでこちらcloseします！　ありがとうございました
