### ISSUE TITLE
Net::HTTPTooManyRequests

### ISSUE THREAD

**Issue by PicoSushi** [decomoji/slack-reaction-decomoji#45]
import_extra.rb実行時に `Net::HTTPTooManyRequests` が出る場合があるようです。適宜ウェイトを挟む必要があるかもしれません。

```
.
.
.
importing zigokukayo...
importing mekarauroko...
importing donokyaraerabimasuka...
Traceback (most recent call last):
        7: from import_extra.rb:87:in `<main>'
        6: from import_extra.rb:15:in `import_decomojis'
        5: from import_extra.rb:55:in `upload_decomojis'
        4: from import_extra.rb:55:in `each'
        3: from import_extra.rb:69:in `block in upload_decomojis'
        2: from /usr/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize.rb:536:in `post'
        1: from /usr/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize.rb:1323:in `post_form'
/usr/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch': 429 => Net::HTTPTooManyRequests for https://....slack.com/api/emoji.add -- unhandled response (Mechanize::ResponseCodeError)
```

**Comment by oti** [comment]
ありがとうございます。ほんとですね……。
Chrome拡張でD&Dする場合でも弾かれてしまうようでした。

いくつごとにどれくらい待てばいいのか謎なのでどうしたらいいかちょっと考えてみます。

**Comment by syguer** [comment]
rate limitにかかった場合に律儀にリトライする処理を入れてみたところ、何秒待っても結局すぐ制限にひっかかってしまい、あまりいい速度がでませんでした
そこで、rate limitにひっかかった場合に思い切ってログインし直すようにしたところ、rate limitがリセットされるようで最初から最後まで体感上ノンストップでさくさく動きました
ただしログインし直す方法の場合、team_name, email, passowrdは再利用できても2段階認証のコードは再利用ができないので、2段階認証が設定されている場合はlate limitによる再ログインのたびにコードを入力する必要があり耐え難いUXとなりました
共有まで

**Comment by oti** [comment]
検証ありがとうございます。本件、今の所どうしようもないな〜くらいの温度感で構えています。どうしたらいいんでしょう……

**Comment by tockn** [comment]
便利なプロダクトを開発してくださりありがとうございます！
TooManyRequestsのヘッダの `retry-after` の時間（2 or 3 sec?）だけsleepするようにしましたが、@syguerさんの仰る通り一度TooManyRequestsに引っかかると再ログインしない限り毎回引っかかるようになりますね。。。（3000個あったら単純計算で2時間くらいかかります。。。）
とりあえず、２段階認証の場合は上記の方法で、それ以外では自動で再ログインするようにしてみましたので、PR投げておきます！

**Comment by oti** [comment]
@tockn さんが改修してくれたスクリプトですと、手元の環境では TooManyRequests が発生しないようになった感じがします。

一応解決したと皆して本件はCloseします。

皆さま、ありがとうございました。
