### ISSUE TITLE
:kouduryokuyutaka: should be :koudouryokuyutaka:

### ISSUE THREAD

**Issue by PicoSushi** [decomoji/slack-reaction-decomoji#46]
https://github.com/decomoji/slack-reaction-decomoji/blob/a36dfe69e4327ea3bcb8bb2164e60c427d4e7910/decomoji/extra/kouduryokuyutaka.png

行動力豊 は koudouryokuyutaka の方が正しそうです。

**Comment by oti** [comment]
@PicoSushi ﾌｧｰ! 完全にそうですね！
ありがとうございます！！:bow:

**Comment by oti** [comment]
fix https://github.com/decomoji/slack-reaction-decomoji/commit/45e8175973170dd95f4ebc172491d2b8d1d5c1d0
