### ISSUE TITLE
心理的安全なサブセット decomoji-safety がほしい

### ISSUE THREAD

**Issue by uknmr** [decomoji/slack-reaction-decomoji#50]
多種多様な人が同じ職場の中で働く中で、好意でいれた emoji も時に人を不快にすることがあるようです。
つかうコンテキストに依りますが、超ハイコンテキストなデコモジだからこそ理解できないまたは不快に感じる人がいてもおかしくないのかもしれません。

ということで安全なデコモジだけをまとめたサブセットをつくれば、この多種多様な人がいる中でも心理的安全を守りつつ超ハイコンテキストなコミュニケーションができるんじゃないかと考えました。

気になるなら base だけ使っとけ（#37） ですかね。
（`extra` でも人を傷つけそうにないならつかいたい、つかいたいんだ）

**Comment by oti** [comment]
そういったサブセットを作る予定はないですね。MITライセンスなので、ここのデコモジを流用して誰でも自由にサブセットを作れますよ。

`extra/` から使いたくないデコモジを削除してからscriptを実行するとか、使いたいデコモジだけ手動で登録するといった方法もあります。

このリポジトリのデコモジ全てをインストールする必要はありませんよ。

**Comment by uknmr** [comment]
了解です。
