### ISSUE TITLE
Readability for Slack dark mode

### ISSUE THREAD

**Issue by PicoSushi** [decomoji/slack-reaction-decomoji#57]
現在slack-reaction-decomojiでは全ての絵文字が背景透過・単色文字で作成されていますが、Slackのダークモードではかなり読みにくくなる（特に黒に近い色の絵文字）という現象を確認しております。

以下は視認性を改善するためのアイディアです：

- 全ての絵文字に背景を設定する
- 縁取りを行う

**Comment by oti** [comment]
この問題は認識しています。

**Comment by oti** [comment]
@PicoSushi いつもありがとうございます。この問題はSlackにダークモードが搭載された瞬間から確認していました。

デコモジのダークモード対応板については、表記ブレや字詰めルールの揺れなどの他のバグもまとめてfixして v5 としてメジャーアップデートでの対応を考えております。

v5 ではデコモジの一括削除機能も搭載するので、それを実行後に対応版をインストールし直してもらうような流れになります。[一括削除機能は`feature/remover` ブランチにあり](https://github.com/decomoji/slack-reaction-decomoji/tree/feature/remover/scripts)、手元でのテストは済んでいる状態です。

どう対応するかはまだ検討中ですが、v5 は年内のリリースを目指しております。引き続きよろしくお願いいたします。

**Comment by oti** [comment]
進捗報告です。結論から言うとカラーパレットを調整する方向で進めています。

---

以下に、ダークモード対応について方法を3つ用意し、それぞれテストファイルで確認したキャプチャを共有します。

1. 文字を縁取りする
2. 背景をベタ塗りする
3. カラーパレットを調整する

一応、既存の見た目のキャプチャを置いておきます。

![stable](https://user-images.githubusercontent.com/710216/68106474-17391300-ff25-11e9-8fbb-6757c48b1648.png)

---

## 1. 文字を縁取りする

デコモジの文字に縁線をつけました。

縁線の太さを 1px, 2px, 3px, 4px 用意しました。一番左は既存の `:akeome:` です。

### 1-a. 白ベタで縁取りする

縁線の色を白ベタ（`#ffffff`）にしてやって見ました。

![stroke](https://user-images.githubusercontent.com/710216/68106477-17391300-ff25-11e9-9700-1d027f2a5d85.png)

ライトモードでは問題ありませんが、ダークモードでは文字内の隙間を縁線が埋めていないところで、小さい黒と白が散らばって、チラチラして見えてしまいます。

隙間を埋めるために縁線をもっと太くすると、画像ファイルの4辺でスッパリ切れてしまう箇所が目立ってきます。一番右の4px縁でよくわかると思います。

`:akeome:` で隙間を全て埋める線の太さは6pxでしたが、それくらいになるともう画像全部に背景色が敷いてあるような見た目になって、それでいて四隅の角丸が字形に沿ったカーブでばらつきがあるため、非常に醜いです。

リアクション時の見た目も、読みづらさが解消されてはおらず、縁線がない方が良いように感じます。

### 1-b. 半透明の白ベタで縁取りする

白ベタなのがいけないのかなと思って半透明バージョンも作って確認しました。

![stroke-opacity](https://user-images.githubusercontent.com/710216/68280105-3916cf00-00b8-11ea-9dc3-ec87f9f0fe76.png)

透明度は白（`#ffffff`）の80%です。透明度が81%以上だと透けすぎで、79%以下では見えすぎに思えたので透明度80%だけ書き出して試しました。

この透明度だと文字間の隙間のチラつきもあまり感じません。しかし、字形と背景の間に中間色ができたようになり、境界がぼやけてしまいました。やったわりには読みやすくはならないと感じます。

----

## 2. 背景をベタ塗りする

### 2-a. 白ベタで背景を塗りつぶす

デコモジの背景を白で塗りつぶしました。

![bg-white](https://user-images.githubusercontent.com/710216/68279960-e806db00-00b7-11ea-836f-4cbd549af399.png)

こちらもライトモードの時は問題ありませんが、ダークモードではちょっと受け入れがたい見た目になります。

文字と文字の距離と、文字と辺の距離が違うので、中心に隙間があって外側が窮屈に感じます。

また、ダークモード上で白ベタを見るとかなりチラチラしますし、これがリアクションで3,4個つくと考えると「文字は読めるが見るに耐えない」ものになるような気がしました。

### 2-b.明るいグレーで背景を塗りつぶす

ライトモードのリアクション時は明るいグレーの上にデコモジが乗ります。なのでその色のバージョンで背景をベタ塗りしたものも作って見ました。

![bg-gray](https://user-images.githubusercontent.com/710216/68279959-e806db00-00b7-11ea-9e30-668e49fd625c.png)

やる必要なかったっぽいです。

----

## 3. カラーパレットを調整する

先に既存（v4）のキャプチャを再掲します。

![stable](https://user-images.githubusercontent.com/710216/68106474-17391300-ff25-11e9-8fbb-6757c48b1648.png)

次がカラーパレットを調整したキャプチャです。

![recolor](https://user-images.githubusercontent.com/710216/68106473-17391300-ff25-11e9-98e7-a2132da5e327.png)

[Solorized](https://ethanschoonover.com/solarized/) を参考に、色相を12パターンにしてコントラスト比を調整しました。

v4 までの元の鮮やかさは失われますが、ライトモードで読めなくなることはないし、ダークモードでの視認性はかなり上がったと思われます。

ただ、ダークモードでリアクションした時（キャプチャの右下）に暗い青色の背景になります。カラーパレットをこれにも対応するのはちょっと不可能に思えたので、**ダークモードでリアクションした時の見た目は諦めます。**

### コントラスト比について

コントラスト比の調整には [HEX Contrast Ratio Calcurator](https://hex-crc.dskd.jp/) を利用しました。

刷新版カラーパレットのコントラスト比は、ライトモードかダークモードの**どちらかで4.5**をとり、また**反転した場合でもほぼ3を維持**するようにしています。

![スクリーンショット 2019-11-03 13 17 42](https://user-images.githubusercontent.com/710216/68080328-7d963680-fe3c-11e9-896c-ed68e9783d18.png)
![スクリーンショット 2019-11-03 13 18 20](https://user-images.githubusercontent.com/710216/68080329-8129bd80-fe3c-11e9-9e4a-b0dde2722940.png)

コントラスト比が全てではありませんし、これが完璧なカラーセットでもありません。もう少し調整をするかもしれません。

----

ということで、カラーパレットを調整してダークモードに対応する方向で進めていきたいと思います。

引き続きよろしくお願いいたします。

**Comment by oti** [comment]
#60

**Comment by oti** [comment]
カラーパレットを刷新した物をv5-preview ブランチに追加していきます。120個
ずつくらいやっていきますので以後はPRの方を追ってください。 #63 

ダークモードに対応する方針は決まっていますので、このイシューは close します。起票ありがとうございました！

**Comment by oti** [comment]
@PicoSushi 大変お待たせしました。 #78 にてようやくダークモード対応版の v5 をリリースできました！　v4 から v5 への移行コマンドも用意しているので、ぜひ使ってみてください！
