### ISSUE TITLE
識別子が重複しているdecomojiが存在した場合にスクリプトが停止してしまう

### ISSUE THREAD

**Issue by sasurai-usagi3** [decomoji/slack-reaction-decomoji#75]
すでにdecomojiが登録されているワークスペースにおいて, decomoji一括登録スクリプトを走らせるた時に重複するdecomoji識別子がすでに存在していた場合スクリプトがクラッシュしてしまうようです...

```
1/5302: uploaded are.
2/5302: uploaded bennri.
3/5302: uploaded buzisibou.
4/5302: uploaded edited.
5/5302: uploaded fabyurasu.
6/5302: uploaded gannbare.
7/5302: uploaded gennkou.
8/5302: uploaded giruthi.
9/5302: uploaded gotidesu.
10/5302: uploaded hai-.
11/5302: uploaded haikonntekisuto.
12/5302: uploaded heisya.
13/5302: uploaded hennziari.
14/5302: uploaded hennzikita.
15/5302: uploaded hennzinasi.
16/5302: uploaded hidariuekakuninn.

(中略...)

47/5302: uploaded ohureko.
48/5302: uploaded onnsya.
49/5302: uploaded reibannnosanngurasu.
50/5302: uploaded sassi.
51/5302: uploaded sasugada.
52/5302: uploaded seyanngu.
53/5302: uploaded sokubukuma.
54/5302: uploaded sonntaku.
55/5302: uploaded sonokotobagakikitakatta.
56/5302: uploaded suko.
57/5302: uploaded syuuryou.
58/5302: uploaded tannome.
59/5302: error_name_taken tanonnda.
[ERROR]Upload failed.
```

**Comment by oti** [comment]
@sasurai-usagi3 イシューありがとうございました。

https://github.com/decomoji/slack-reaction-decomoji/commit/89f209b82b05c1489184ebc64e0bf47c675b5245 にて、error_name_taken の場合はスキップして処理を続行するように修正しました。

スクリプトの仕様としては、対象のワークスペースにすでに追加してあるカスタム絵文字リストを全て受領したのち、追加しようとしているデコモジのファイル名と重複しないものだけを抽出して追加処理を実行するようになっていまして、そもそも error_name_taken のエラーは起きないはずなのですが、どうやらワークスペースのカスタム絵文字を取り漏れる場合があるようです。取り漏れているかどうか判定することができないため、このような対応になりました。

デコモジをご利用いただきましてありがとうございます。引き続きよろしくお願いいたします。

**Comment by oti** [comment]
@sasurai-usagi3 先日は報告ありがとうございました。

対応したとお知らせしていた https://github.com/decomoji/slack-reaction-decomoji/commit/89f209b82b05c1489184ebc64e0bf47c675b5245 では登録が1件で終わってしまうエンバグがありまして、対応が不十分でした。

先ほど #76 にて修正されたものを取り込みましたので、お手元の master ブランチを最新にしてお試しください。

ご迷惑おかけしました:bow:
