### ISSUE TITLE
「EUC_JP」という表記

### ISSUE THREAD

**Issue by myakura** [decomoji/slack-reaction-decomoji#83]
![画像：v5のEUC_JPというデコモジ](https://user-images.githubusercontent.com/413984/88765721-dd462600-d1b1-11ea-91bc-4cb7b25baec1.png)
https://github.com/decomoji/decomoji/blob/v5.0.0/decomoji/extra/euc_jp.png

このデコモジがあったのを先ほど知りました。
ただ、連想するエンコーディングの表記は「EUC-JP」なので、違和感があります。

https://ja.wikipedia.org/wiki/EUC-JP

Encoding仕様でも、アンダースコアのほうはラベルとして登録されていません。
https://encoding.spec.whatwg.org/#ref-for-euc-jp
（Shift_JISはハイフンのやつもラベルとして認識されるらしいですが）

**Comment by oti** [comment]
これは完全にミスですね。ありがとうございます！

ファイル名も変わるので、v5.2 の対応とさせてください。遅くとも来月中にはリリースします！

**Comment by oti** [comment]
#84 で修正しました。報告ありがとうございました！
