### ISSUE TITLE
nameの綴りをヘボン式でも入力できるようにしてほしいです

### ISSUE THREAD

**Issue by h-yon** [decomoji/slack-reaction-decomoji#88]
「終了」(syuuryou) は shuuryou , 「ﾁｮｯﾄﾃﾞｷﾙ」(tyottodekiru) は chottodekiru のように拗音は綴りをヘボン式でも入力できるようにjson内でduplicateを作ってほしいです。

**Comment by geckotang** [comment]
@ploodstone 任意の名前でエイリアスを作る機能を提供していますが、そちらでは不十分でしょうか。

https://github.com/decomoji/decomoji/blob/master/docs/ADVANCED.md#%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%81%AE%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%82%B9%E3%82%92%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B

**Comment by h-yon** [comment]
その機能あったんですね。ちゃんと見てませんでした
